#!/usr/bin/env bash

# Copyright 2019 Victor Hugo Schulz

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

mkdir -p hipparcos
cd hipparcos
wget ftp://cdsarc.u-strasbg.fr/pub/cats/I/239/hip_main.dat.gz
wget ftp://cdsarc.u-strasbg.fr/pub/cats/I/311/hip2.dat.gz
gunzip hip_main.dat.gz
gunzip hip2.dat.gz
