#!/usr/bin/env python3

# Copyright 2019 Victor Hugo Schulz

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys
sys.path.append("src/data_processing")

from src.data_processing.data_processing import *

star_id_histogram_run()
# star_tracker_position_run()
# star_tracker_magnitude_run()
# star_tracker_false_stars_run()
# star_tracker_focus_std_run()
# star_tracker_focus_dc_run()
# star_tracker_grid_size_run()
# star_tracker_position_triple_run()
# star_tracker_magnitude_triple_run()
# star_tracker_false_stars_triple_run()
# star_tracker_focus_std_triple_run()
# star_tracker_focus_dc_triple_run()
# star_tracker_grid_size_triple_run()

star_id_histogram_plot()
# star_tracker_position_plot()
# star_tracker_magnitude_plot()
# star_tracker_false_stars_plot()
# star_tracker_focus_std_plot()
# star_tracker_focus_dc_plot()
# star_tracker_grid_size_plot()
# star_tracker_position_triple_plot()
# star_tracker_magnitude_triple_plot()
# star_tracker_false_stars_triple_plot()
# star_tracker_focus_std_triple_plot()
# star_tracker_focus_dc_triple_plot()
# star_tracker_grid_size_triple_plot()

# attitude_error_run()
